# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('img', 'Image'), ('vid', 'Video'), ('aud', 'Audio'), ('txt', 'Text')], max_length=120)),
                ('file', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
