# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_auto_20180719_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='test',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
